name: Publish coverage at Codecov
on: [push]

jobs:
  run:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-versions:
          - 14

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/cache@v2
        id: cache
        with:
          path: node_modules/
          key: ${{ runner.os }}-node${{ matrix.node-version }}-${{ hashFiles('yarn*.lock') }}

      - run: yarn ci
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Generate coverage report
        run: yarn test:coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          flags: unittests
          env_vars: OS,NODE
          name: codecov-umbrella
          fail_ci_if_error: true
