name: Linting and Testing
on: [push, pull_request]

jobs:
  run:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-versions:
          - 10
          - 12
          - 14

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/cache@v2
        id: cache
        with:
          path: node_modules/
          key: ${{ runner.os }}-node${{ matrix.node-version }}-${{ hashFiles('yarn*.lock') }}

      - run: yarn ci
        if: steps.cache.outputs.cache-hit != 'true'

      - run: yarn test:ci
      - run: yarn lint