name: CI
on: [push]
jobs:
  build:
    name: Node ${{ matrix.node }} sample
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12', '14', '15' ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: yarn install
      - run: yarn lint
      - run: yarn test
